### PR TITLE
HW done

### PR DESCRIPTION
**Pull request by Au-Rikka**
Максимовских Анастасия, группа m3339

statement optimization + transaction optimization

tested on Lenovo S850:
without optimizations: 1698,31s
with both of them: 45,45s (also worked 51,29s)

### CODE REVIEW

**Comment by artemohanjanyan** [comment]
А скриншот? :anguished:

**Comment by Au-Rikka** [comment]
Нужен скриншот?
ensu6jcxwzu

**Comment by artemohanjanyan** [comment]
Традиция

**Comment by dtrounine** [comment]
Принято

**Pull request closed without merging**
